### PR TITLE
Fix a test for root_commit.parent

### PR DESCRIPTION
**Pull request by heavywatal**
The previous PR #11 had a bug: `commits.first` is the latest commit.

But `commits.last` is, however, not always the root commit because it passes `max_count = 10` to `git.log` by default.

### CODE REVIEW

**Comment by dometto** [comment]
> But commits.last is, however, not always the root commit because it passes max_count = 10 to git.log by default.

Nice catch again. Do you know if for the test repo for this spec suite, `repo.commits.last` would actually be the last commit?

Alternatively, I guess you could write the test as a loop, calling `.parent` on each commit until it breaks. 😄

**Comment by heavywatal** [comment]
> Do you know if for the test repo for this spec suite, repo.commits.last would actually be the last commit?

It looks ok for now. There are only four commits:

```
% git log --all --oneline -C spec/fixtures/dot_bare_git
6506f6f New example with renamed file
46b8ea0 (origin/grep_specs) Cleanup fixture repo, redefine expectations
483df4e Add search specs and example files
55db063 Initial commit of Gollum Git adapter specifications.
```

> Alternatively, I guess you could write the test as a loop, calling .parent on each commit until it breaks. 😄

Good idea. The following code is the best I can do. Should we adopt it, or keep the current one?

```ruby
    until commit.nil?
      expect(commit).to be_a Gollum::Git::Commit
      commit = commit.parent
    end
```

**Comment by dometto** [comment]
> Good idea. The following code is the best I can do. 
Looks like it would work, if you add an expectation below there:

```ruby
expect(commit).to be_nil
```

@bartkamphorst what do you think the most transparent way of testing this would be?

**Comment by bartkamphorst** [comment]
Going through all commits recursively like that only slows testing down without adding anything substantive. I would opt to keep the previous way of testing with `commits.last`, and just add an assertion that `commits.size < 10` as a contingency check for the future (in case the test repo is extended).

**Comment by dometto** [comment]
>  just add an assertion that commits.size < 10 as a contingency check for the future (in case the test repo is extended).

Good idea, thanks!

**Comment by heavywatal** [comment]
It seems impossible to test true log lengths using only the functions defined in the current adapter specs, e.g., `commits.size < 10` does not work as expected because the result of `commits` is already truncated with `max_count = 10`.

Both the `repo.commits` of rugged_adapter and rjgit_adapter happen to have the second argument `max_count` in common. So if we can add it to the specs, the following code will do:
```ruby
expect(repo.commits('master', 2 ** 31).last.parent).to eq nil
```

**Comment by dometto** [comment]
> It seems impossible to test true log lengths using only the functions defined in the current adapter specs, e.g., commits.size < 10 does not work as expected because the result of commits is already truncated with max_count = 10.

But if we're testing for `< 10` (or even more specifically, `== 4`, it shouldn't matter that the commits are potentially truncated, no? It's just meant to provide an indication that the tests are not functioning as we want them if there are more than X commits.

**Comment by heavywatal** [comment]
Fair enough. I was taking it too hard.

**Comment by dometto** [comment]
Thanks!

**Comment by dometto** [comment]
Sorry @heavywatal, just noticed the test repo actually has more than 10 commits, so ended up fixing it like [this]( https://github.com/gollum/adapter_specs/commit/96795752777791001fdb10ed9a2fe0dfce2121b7)

**Pull request merged**
